# Generated by Django 4.1.7 on 2023-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(default='null', upload_to='', verbose_name='Makale Görseli'),
            preserve_default=False,
        ),
    ]
